#!/usr/bin/env bash

ENV_SCRIPT=./set_order.sh

if [ -e "$ENV_SCRIPT" ]; then
    source $ENV_SCRIPT
else 
    echo "Environment file does not exist: $ENV_SCRIPT"
    exit 1
fi 

brazil workspace --sync

for package in $(echo $ORDERED_PACKAGES| sed "s/,/ /g")
do
    pushd $package
    (brazil-build | highlight "error|ERROR|Error|fail|FAIL|Fail") || exit $?
    popd
done
